### ISSUE TITLE
"optional" column tracking_type

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/ObsLocTAP#24]
I have some comments about the introduction of the new field `tracking_type` from PR #23.  Since this was proposed and accepted during the interop when things were quite busy, I didn't have the time to comment on it before it was merged.

Unlike all the other fields, its "Constraint" in table 1 is listed as "Optional field", and the text in Sec 3.1 also says:

> Tracking type (\textbf{tracking\_type}) is an optional field of the obsplan table

It's not explained exactly what that means, but if it is is supposed to mean that the column may be omitted in the obsplan table, then it conflicts with the text earlier in Sec 3.1:

> The obsplan table exposed by an ObsLocTAP service MUST include all the columns listed, even though null values may be permitted in some of the columns.

I strongly suggest that this column should follow the others in being mandatory (though with null values permitted), since dealing with columns that may be absent makes it much harder for clients to query such values.

Plus one minor point: the tracking_type item in the LaTeX source for Table 2 is labelled `%row no: 24` but should be `%row no: 27`.

**Comment by jesusjuansalgado** [comment]
Yes, I see that adding an optional field is a problem but we hesitated as the fact that we are adding an extra field would make the implementations non fully compatible. This field is going to be empty for most of the services.

The two options I see are:
- Maintain it as optional but modify the sentence where it says that all columns should appear (in this case current implementations are still valid)
- As proposed, add it as compulsory and allow a null value

How bad could it be to have this discrepancy on the table from the operational group point of view?

**Comment by mbtaylor** [comment]
@jesusjuansalgado, you're right that the existing reference implementations become invalid if this new column is made compulsory, therefore it would be necessary to update and revalidate them, and so I can see why you're reluctant to do it.

But the problem is that if this column may or may not be present, then clients can't pose the same query to all ObsLocTAP services.  If you want to do something like select for sidereal tracking, you would have to do significant additional work examining the TAP metadata of a given service before working out what ADQL to present.

ObsCore does not contain any optional columns, to avoid these problems.  EPN-TAP contains several categories of them, so there is (at least in draft) precedent for this sort of thing, but in EPN-TAP it looks like they have been thought out fairly carefully, while having the single column `tracking_type` marked as optional looks like, well, a messy hack to speed acceptance of the standard (and incidentally, added after most TCG members have already read and commented on the document).  If you and the other authors can live with that, and feel that the impact on ObsLocTAP users will be acceptable, I'm not going to block acceptance as long as the text is clarified appropriately.  But I would be interested in the opinions of other TCG (ex-)members on the author list, e.g. @msdemlei and @molinaro-m.

**Comment by jesusjuansalgado** [comment]
@mbtaylor I will contact the two teams that have reference implementations to see how difficult is for them to add the new column (to evaluate the impact) and with this info, we could take a decision
In principle, the change looks small but I imagine it would just depend on the resources at this particular point

**Comment by jesusjuansalgado** [comment]
Chandra and Integral teams contacted

**Comment by msdemlei** [comment]
On Tue, Jun 08, 2021 at 09:51:00AM -0700, Mark Taylor wrote:
> live with that, and feel that the impact on ObsLocTAP users will be
> acceptable, I'm not going to block acceptance as long as the text
> is clarified appropriately.  But I would be interested in the
> opinions of other TCG (ex-)members on the author list, e.g.
> @msdemlei and @molinaro-m.

I'm always in favour of removing optional things, either by dropping
them or by making them mandatory, and so I'm sympathetic to the
general plan.

However, if you make it mandatory, it certainly needs to be in the
reference implementations -- if they don't put it in now, it'll be an
endless annoyance, in particular when clients start implementing
against what's there.  Once the column is in them, I think it's fine
making the last-minute change, informing the TCG about it in a short
writeup, giving people a week to protest (I'm sure nobody will) and
then going ahead with the REC.

**Comment by jesusjuansalgado** [comment]
@mbtaylor @msdemlei 
Both reference implementations development teams (Chandra and Integral) has agreed to modify their implementations so I will modify the spec to put it as compulsory what, in principle, is the preference of all

**Comment by molinaro-m** [comment]
I'm happy this solved before I had the time to comment. I was on the same lines as @msdemlei and I'm happy the reference implementations are able to cope with the change. Thanks!

**Comment by mbtaylor** [comment]
Great, thank you @jesusjuansalgado (and implementation developers).  Once the document text is modified to reflect this change, I will make available an updated taplint validator.

**Comment by jesusjuansalgado** [comment]
Thanks, @mbtaylor!

**Comment by mbtaylor** [comment]
One minor stylistic note: in the current text the permitted values for tracking_type are all lower case (e.g. `sidereal`, `fixed-az-el-transit`, while values for other enumeration columns start with upper case (e.g. `Planned`, `Coordinated`).  That's not a major problem, I just mention it in case you wanted to take the opportunity to homogenise the style.

**Comment by mbtaylor** [comment]
Addressed by PR #25.
