### ISSUE TITLE
Case-sensitivity of obsplan table utype matching

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/ObsLocTAP#26]
Section 5 requires:
> ... the ivoa.obsplan table’s utype set to:
>        ivo://ivoa.net/std/ObsLocTAP#table-1.0.

but the following RegTAP query includes the WHERE clause
```
   table_utype=’ivo://ivoa.net/std/obsloctap#table-1.0’
```
The RegTAP query has to be in lower case because of requirements in the RegTAP standard.  Currently the `/tables` document of the Integral reference implementation marks the ivoa.obsplan table with `<utype>ivo://ivoa.net/std/obsloctap#table-1.0</utype>` which is technically in breach of the standard, since the value is not (case-sensitively) identical to the requirement.  To avoid that kind of confusion (and avoid having to modify the Integral implementation) I'd suggest _either_ changing the utype requirement to an all-lower-case value, _or_ making it clear that the matching is not case-sensitive.

**Comment by jesusjuansalgado** [comment]
Implemented into
https://github.com/ivoa-std/ObsLocTAP/pull/27

**Comment by jesusjuansalgado** [comment]
@mbtaylor could you please alert the Chandra team about this change?

**Comment by mbtaylor** [comment]
I have sent email to Michael Tibbetts as requested.
